[package]
name = "nvidia_cuda"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
cudarc = { version = "0.17.3", features = ["std", "nvrtc", "cuda-13000", "driver"]}
nvtx = "1.3.0"
